### ISSUE TITLE
create single common repo for ext deps

### ISSUE THREAD

**Issue by progaddict** [EmbeddedMontiArc/external-dependencies#1]
### Problem
[example-autopilot-ema](https://github.com/MontiSim/example-autopilot-ema) uses [EMA2Kotlin](https://github.com/EmbeddedMontiArc/EMA2Kotlin), which is installed by Travis to this repo and **not** to https://github.com/MontiSim/external-dependencies where the [example-autopilot-ema](https://github.com/MontiSim/example-autopilot-ema) looks for its ext deps. Moreover, there are also _transitive_ deps e.g. [EmbeddedMontiArc](https://github.com/EmbeddedMontiArc/EmbeddedMontiArc) and [Struct](https://github.com/EmbeddedMontiArc/Struct) (the [EMA2Kotlin](https://github.com/EmbeddedMontiArc/EMA2Kotlin) needs the Parsers, SymbolTables and other stuff from them).

### Possible Solution #1
create a single repo with all the ext deps and let Travis push all the artifacts to it.

### Possible Difficulties #1
❓ can locking be a problem here, when multiple Travis jobs try to push at the same time?
❓ can these multiple Travis jobs bring the single repo to an inconsistent state? in other words, does git support transactions/locking at all?

### Possible Solution #2
Use a public maven server for uploading artifacts, see [free-for-dev](https://github.com/ripienaar/free-for-dev#artifact-repos).
E.g. this one: [central.sonatype.org](http://central.sonatype.org/pages/ossrh-guide.html#deployment)
Set up Travis to deploy artifacts to a chosen public maven sever.

### Possible Difficulties #2
😃 finding a DevOps person who will invest his/her time into that. everyone needs to do his piece of work (generator, building models, refactoring etc.) and therefore nobody has time for that. However, I believe we need someone who will do the DevOps part, at least in the beginning.
❓ how to coordinate Travis builds, taking into account changes of external deps? E.g. when Struct changes then EmbeddedMontiArc needs to be rebuilt or when both of them change at the same time then Travis needs to build Struct first and then EmbeddedMontiArc.

I am looking forward to discussing it with you. Better, probably, right here in the issue (i.e. not via emails) because GitHub will save our discussion for future reference (whereas emails are cleaned up regularly).

**Comment by sschneiders** [comment]
What about changing your project to fetch dependencies from both locations?

**Comment by progaddict** [comment]
That's a good idea. I am not sure it is possible though. I'll investigate it

**Comment by progaddict** [comment]
Tomorrow I'll try to use separate the maven requests. I'll create two mirrors for two ext deps repos: one for EMA projects and the second one for MontiSim.
@sschneiders  I'd like to ask you to add password to the Struct and to the example-autopilot-ema :) Also, do you know if Travis can fetch deps from public repositories? I presume not, because otherwise you would not do a mirror for everything (with wildcard *)

**Comment by sschneiders** [comment]
As far as i know, you can add several mirrors, but these will only be tried for resolution if the dependency could not be resolved in the previous/first mirrors.

I already added the key to the struct project.
However, for some reason I am currently not able to change the settings of the example-autopilot-ema project, therefore i can not add the key currently.

**Comment by progaddict** [comment]
@sschneiders 
hmm... maybe it is because of the default read permission in the repository...
I've added you to the collaborators with write access

**Comment by progaddict** [comment]
does anyone know if the site plugin supports the GitHub API tokens?
https://github.com/blog/1509-personal-api-tokens
then maybe I could create a token and add it myself everywhere where I need Travis to push artifacts.
I'll investigate it... after I finish fixing the build 😃

**Comment by sschneiders** [comment]
@progaddict 
I dont know what the issue with travis was, but after restarting chrome I was able to add it.
(I already had write permissions so it was not related to that)
If I remember correctly, someone has told me that travis can also work with tokens. So it should be possible.

**Comment by progaddict** [comment]
use multiple maven repositories/servers
